# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
# User specific aliases and functions
alias grep='grep --exclude-dir={.bzr,CVS,.git,.hg,.svn} --color=auto'
alias grepex='grep -Ir -n --exclude=cscope.out --exclude=tags --exclude=.files --exclude-dir={.bzr,CVS,.git,.hg,.svn} --color=auto'
alias grepc='grep -Ir -n --exclude=cscope.out --exclude=tags --exclude-dir={.bzr,CVS,.git,.hg,.svn} --include=*\.{c,h}* --color=auto'
alias grepcpp='grep -Ir -n --exclude=cscope.out --exclude=tags --exclude-dir={.bzr,CVS,.git,.hg,.svn} --include=*\.{cpp,hpp}* --color=auto'

